server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aadhaar
    username: root
    password: Ashish@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
